### ISSUE TITLE
convert periodics repo from subversion to git

### ISSUE THREAD

**Issue by dlangille** [FreshPorts/periodics#3]
Take `https://svn.freshports.org/viewvc.cgi/freshports-1/periodics/` and convert it to `git`

**Comment by dlangille** [comment]
Anyone: feel free to take this on.

**Comment by calebpower** [comment]
Do you care to preserve the svn history? Or are we just migrating files as they are?

**Comment by dlangille** [comment]
I'd prefer to preserve history.

**Comment by dlangille** [comment]
I think progress here is dependent upon FreshPorts/ports#1 allowing a command line checkout - I want anonymous checkouts so anyone can 'clone' the repo and take it from there.

**Comment by dlangille** [comment]
Yeah, that's not enough. I need to run `svnadmin dump` or just make the whole repo downloadable.

**Comment by dlangille** [comment]
If someone wants to do the research, document the approach, and tell me what you need, I'll run the commands.  Or, I can provide the raw repo for download so you can do it all on your own without me. ;)

**Comment by dlangille** [comment]
After installing `devel/git-svn` I've been following https://www.gitkraken.com/blog/migrate-from-svn-to-git-guide#import-and-preserve-history

**Comment by dlangille** [comment]
so far, and now I'm waiting:

```
[1:14 svn dvl ~/svn-to-git/git] % git svn clone file:///usr/home/dvl/svn-to-git/repo/ --no-metadata --authors-file=author-transformed.txt --stdlayout freshports-1
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /usr/home/dvl/svn-to-git/git/freshports-1/.git/
Found possible branch point: file:///usr/home/dvl/svn-to-git/repo/periodics/trunk => file:///usr/home/dvl/svn-to-git/repo/tags/1.0.0, 4914
Initializing parent: refs/remotes/origin/tags/1.0.0@4914
W: Ignoring error from SVN, path probably does not exist: (160013): Filesystem has no item: File not found: revision 101, path '/periodics/trunk'
W: Do not be alarmed at the above message git-svn is just searching aggressively for old history.
This may take a while on large repositories
Found possible branch point: file:///usr/home/dvl/svn-to-git/repo/periodics => file:///usr/home/dvl/svn-to-git/repo/periodics/trunk, 4910
Initializing parent: refs/remotes/origin/tags/1.0.0@4910
W: Ignoring error from SVN, path probably does not exist: (160013): Filesystem has no item: File not found: revision 101, path '/periodics'
W: Do not be alarmed at the above message git-svn is just searching aggressively for old history.
This may take a while on large repositories
Checked Ahrough README.txt
r4910 = 81d4fb40f2ab8df262be0b158da301d6709dbaa3 (refs/remotes/origin/tags/1.0.0@4910)
Found branch parent: (refs/remotes/origin/tags/1.0.0@4914) 81d4fb40f2ab8df262be0b158da301d6709dbaa3
Following parent with do_switch
Successfully followed parent
r4911 = 226ed1b4ee9c7a946fdb6883d40e0eedb1a42bd6 (refs/remotes/origin/tags/1.0.0@4914)
	A	100.fp_archive_messages
r4913 = afbf7f3a58515f491d9ed8f23ef3109807a3c95a (refs/remotes/origin/tags/1.0.0@4914)
Found branch parent: (refs/remotes/origin/tags/1.0.0) afbf7f3a58515f491d9ed8f23ef3109807a3c95a
Following parent with do_switch
Successfully followed parent
r4915 = 6103912c898c8042457fe5e6d9fd86037069fcd9 (refs/remotes/origin/tags/1.0.0)
fatal: refs/remotes/origin/trunk: not a valid SHA1
update-ref HEAD refs/remotes/origin/trunk: command returned error: 128

[1:17 svn dvl ~/svn-to-git/git] % 
```

It seems to have barfed.

**Comment by dlangille** [comment]
This time I tried:

```
[1:45 svn dvl ~/svn-to-git/git] % git svn clone file:///usr/home/dvl/svn-to-git/repo/ --authors-file=author-transformed.txt  freshports-1
Initialized empty Git repository in /usr/home/dvl/svn-to-git/git/freshports-1/.git/
W: +empty_dir: www/branches
W: +empty_dir: www/tags
W: +empty_dir: www/trunk
r1 = a382fe522689ac2c32ead1b2126821551e6dbdea (refs/remotes/git-svn)
	A	www/trunk/_private/commonlogin.php3
	A	www/trunk/_private/freshports.php3
	A	www/trunk/_private/getvalues.php3
	A	www/trunk/_private/login.inc.php3
	A	www/trunk/_private/new-user.inc

...

creating empty directory: periodics/tags/1.0.9/monthly
creating empty directory: ports/branches
creating empty directory: scripts-fp2/branches
creating empty directory: walkports/branches
[2:00 svn dvl ~/svn-to-git/git] % 
[2:00 svn dvl ~/svn-to-git/git] % cd freshports-1 
[2:07 svn dvl ~/svn-to-git/git/freshports-1] % ls
api.freshports.org/ convert/            db-conversion/      include/            ports/              walkports/
backend/            daemontools/        develop/            ingress/            scripts-fp2/        www/
classes/            database-schema/    docs/               packaging/          scripts.ARCHIVE/
configuration/      dataconversion/     fwatch/             periodics/          secure/
[2:07 svn dvl ~/svn-to-git/git/freshports-1] % 
```

**Comment by dlangille** [comment]
oh, but this isn't right:

```
commit ce3b248b34e804ef6ed6a0b7988b84708826105b
Author: Dan Langille <dan@langille.org>
Date:   Wed Nov 27 16:48:38 2024 +0000

    'fix ports being deleted on branches'
    
    git-svn-id: file:///usr/home/dvl/svn-to-git/repo@6140 46e82423-29d8-e211-989e-002590a4cdd4
```

**Comment by dlangille** [comment]
@calebpower I have uploaded the results to a private repo and given you access. This may be harder than I thought.

Many of the top level directories in `freshports-1` should be separate git repos. I'm not yet sure how to achieve that.

**Comment by calebpower** [comment]
I was doing a little research on some svn to git import methods... my concern was that it might be a bit of a mess to try to convert svn over to git on top of an existing repo. Referencing [this article](https://www.gitkraken.com/blog/migrate-from-svn-to-git-guide), I was going to try the following steps:

1. Download the newly-published SVN repo and convert it using `git svn clone` + some `sed` magic and push it into `calebpower/freshports-periodics-svn`
2. Fork `freshports/periodics` into `calebpower/freshports-periodics` (I've done this step first, out of order).
3. Try to set an upstream for `calebpower/freshports-periodics` to `calebpower/freshports-periodics-svn` and do some rebase magic to try to preserve history.

But, step 3 might be more convoluted (since it involves rebasing) and really just represents my desire to PR into `freshports/periodics`... it might perhaps be easier to (a) provide freshports access to a fresh repository without files committed or (b) ask you to just fork it from `calebpower/freshports-periodics` into a blank repository after the fact, so that we don't have to deal with the existing history of the LICENSE file in the current git repo.

This all of course would be required only if you want to preserve history... without it, it's probably just a matter of downloading the files and pushing them up.

Okay, so that's the "second" hurdle to figure out... the "first" hurdle is, for whatever reason I'm having a problem actually pulling files from the new freshports svn repo... some research indicates that maybe viewvc doesn't support this, but does support a toggle to enable a tarball download... but more likely this is just PEBCAK on my end (as I haven't touched svn in probably over a decade at this point).

```
[cpower@matrix ~/projects/code/freshports]$ rm -rf *
[cpower@matrix ~/projects/code/freshports]$ git svn clone https://svn.freshports.org/freshports-1/periodics -T trunk -b branches -t tags
Initialized empty Git repository in /data/projects/code/freshports/periodics/.git/
Can't create session: Unable to connect to a repository at URL 'https://svn.freshports.org/freshports-1/periodics': The server at 'https://svn.freshports.org/freshports-1/periodics' does not support the HTTP/DAV protocol at /usr/local/lib/perl5/site_perl/Git/SVN.pm line 310.
```

Supposedly, `git svn` has some nifty auto-conversion functionality that I'd like to take advantage of.

**(it is as this point that I actually read the comments you posted above, wherein I discovered you've done similarly)** -- but I see that you're pulling it using a "file://" protocol ... and it's at this point that I've seen the private repo you've created, heh

**Comment by calebpower** [comment]
One thing that we could do, since it seems you've been successful preserving history, is some busywork... ultimately, converting that monorepo into a bunch of smaller repos.

Steps:

1. For each directory $prj, fork private repo to a new repo at freshports/$prj
2. For each new repo freshports/$prj, move $prj/trunk/* to root and delete all other files

A little manual, but shouldn't take too long if you think that's the appropriate way forward.

**Comment by calebpower** [comment]
I would like to try the following steps as a proof, on `freshports/periodics` if it's alright with you. The steps I'd take would be:

1. Clone the private repo.
3. Force-push the history of the private repo into the `main` branch.
4. Move `periodics/trunk/*` to the root and remove everything else.
5. Recopy LICENSE over if it doesn't exist into the root of the main branch.

I'm afraid that with conflicting histories a PR wouldn't play out very well.

I'd need elevated access to `freshports/periodics` but the risk (considering I'm a new committer and we don't know each other very well) should be minimum since this repo is essentially empty anyhow.

**Comment by dlangille** [comment]
Elevated access granted. :)

**Comment by calebpower** [comment]
Murphy strikes again...

```
[cpower@matrix ~/projects/code/freshports]$ git clone --mirror git@github.com:FreshPorts/freshports-1
Cloning into bare repository 'freshports-1.git'...
remote: Enumerating objects: 39700, done.
remote: Total 39700 (delta 0), reused 0 (delta 0), pack-reused 39700 (from 1)
Receiving objects: 100% (39700/39700), 18.01 MiB | 6.99 MiB/s, done.
Resolving deltas: 100% (22693/22693), done.
[cpower@matrix ~/projects/code/freshports]$ cd freshports-1.git/
[cpower@matrix ~/projects/code/freshports/freshports-1.git]$ ls
HEAD		branches	config		description	hooks		info		objects		packed-refs	refs
[cpower@matrix ~/projects/code/freshports/freshports-1.git]$ git push --mirror git@github.com:FreshPorts/periodics
ERROR: Permission to FreshPorts/periodics.git denied to calebpower.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by dlangille** [comment]
Run a `find` - there's nothing in there. I did the same `git clone`.

**Comment by dlangille** [comment]
However, without `--mirror`:

```
[19:37 mydev dvl ~/tmp] % git clone git@github.com:FreshPorts/freshports-1.git     

Cloning into 'freshports-1'...
remote: Enumerating objects: 39700, done.
remote: Total 39700 (delta 0), reused 0 (delta 0), pack-reused 39700 (from 1)
Receiving objects: 100% (39700/39700), 18.01 MiB | 18.29 MiB/s, done.
Resolving deltas: 100% (22693/22693), done.
Updating files: 100% (28453/28453), done.
[19:37 mydev dvl ~/tmp] % ls freshports-1
README.md           configuration/      dataconversion/     fwatch/             periodics/          secure/
api.freshports.org/ convert/            db-conversion/      include/            ports/              walkports/
backend/            daemontools/        develop/            ingress/            scripts-fp2/        www/
classes/            database-schema/    docs/               packaging/          scripts.ARCHIVE/
[19:37 mydev dvl ~/tmp] % 
```

**Comment by calebpower** [comment]
Oh yeah I mean I think that might just be how `--mirror` works, supposedly it's just raw. That's the workflow I use to mirror things from Bitbucket to GitHub, anyhow. But even without it:

```
[cpower@matrix ~/projects/code/freshports/bonemesh.git]$ history
  547  git clone git@github.com:freshports/freshports-1
  548  cd freshports-1/
  549  ls
  550  git submodule ls # out of curiosity
  551  ls
  552  nano -cw .git/config # here, modified the origin URL to git@github.com:freshports/periodics
  553  git push --force
```

```
ERROR: Permission to freshports/periodics.git denied to calebpower.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by calebpower** [comment]
Oh "bonemesh" above in my pwd... I was just mirroring another repo that I know for certain mirrors correctly and I had a similar directory structure.

**Comment by dlangille** [comment]
Ahh, the `periodics` repo, yes, I was still stuck in `freshports-1` in my head. Please try again.

**Comment by calebpower** [comment]
Sweet. Okay, I've done that to `periodics`, if you're happy with that I can get the others squared away if you want.

**Comment by dlangille** [comment]
I'm AFK until tomorrow. FYI.

**Comment by calebpower** [comment]
No worries. My schedule is super odd and sort of around-the-clock so I'll be around whenever.

**Comment by dlangille** [comment]
Online, via phone. The repo has nil history, from the few files I checked. 

I was thinking about this last night, and I thought that if we imported everything, then deleted the files we didn't need, we would still have the history of all the other files we had deleted. 

I can't imagine we are the first ones to try and solve this particular issue of history. 

I'm sure we did this when we imported the www code. If you look in the freshports-1 repo, there should be a www directory which became the FreshPort repo. I has help on that one too. 

I'll read/ask around.

**Comment by calebpower** [comment]
hmmm... here's what I see on my side:

```
# fresh clone
[cpower@matrix ~/projects/code/freshports]$ git clone git@github.com:FreshPorts/periodics
Cloning into 'periodics'...
remote: Enumerating objects: 39703, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 39703 (delta 0), reused 3 (delta 0), pack-reused 39700 (from 1)
Receiving objects: 100% (39703/39703), 18.01 MiB | 7.18 MiB/s, done.
Resolving deltas: 100% (22693/22693), done.
[cpower@matrix ~/projects/code/freshports]$ cd periodics/
[cpower@matrix ~/projects/code/freshports/periodics]$ git log

commit 40afdb78dc70a8f2579d4c878202bae42240216a (HEAD -> main, origin/main, origin/HEAD)
Author: Caleb L. Power <cpower@axonibyte.com>
Date:   Wed Dec 18 17:56:58 2024 -0500

    move periodics/trunk to root, wipe the rest; add license

commit b8fe7be5a43579a11e81c5f8da1f2ff31a179e18
Author: svnusers <dvl@svn.freshports.org>
Date:   Wed Dec 18 02:13:28 2024 +0000

    first git commit

commit ce3b248b34e804ef6ed6a0b7988b84708826105b
Author: Dan Langille <dan@langille.org>
Date:   Wed Nov 27 16:48:38 2024 +0000

    'fix ports being deleted on branches'

    git-svn-id: file:///usr/home/dvl/svn-to-git/repo@6140 46e82423-29d8-e211-989e-002590a4cdd4

commit 73ba2ffdaaea8f2884c23b3b8ad51852244ea705
Author: Dan Langille <dan@langille.org>
Date:   Wed Nov 27 16:46:46 2024 +0000

    'adding debugging, invoke dispose()'

    git-svn-id: file:///usr/home/dvl/svn-to-git/repo@6139 46e82423-29d8-e211-989e-002590a4cdd4

commit c156c09b38b5d645d7030ce425aba4f201420ccf
Author: Dan Langille <dan@langille.org>
Date:   Wed Nov 27 16:23:44 2024 +0000

    verifyport.pm: fix ports being deleted on branches

    re: https://github.com/FreshPorts/freshports/issues/528

    If the port is deleted, but set active, set it deleted.
    After saving the port, make sure we adjust the {status} flag:

    If the status changes, set it back to what it was

    see https://news.freshports.org/2024/11/27/when-a-port-on-a-branch-is-deleted-freshports-tried-and-fails-to-refresh-it/



    git-svn-id: file:///usr/home/dvl/svn-to-git/repo@6138 46e82423-29d8-e211-989e-002590a4cdd4

# ...
```

Is there another history listing I should look at instead?

**Comment by calebpower** [comment]
And with `--follow` included on a specific file:

```
[cpower@matrix ~/projects/code/freshports/periodics]$ git log --follow README.txt
commit 40afdb78dc70a8f2579d4c878202bae42240216a (HEAD -> main, origin/main, origin/HEAD)
Author: Caleb L. Power <cpower@axonibyte.com>
Date:   Wed Dec 18 17:56:58 2024 -0500

    move periodics/trunk to root, wipe the rest; add license

commit be8f882b80512e8ab85ca170de0a59d8147baf04
Author: Dan Langille <dan@langille.org>
Date:   Wed Oct 25 15:21:33 2017 +0000

    mv to correct location



    git-svn-id: file:///usr/home/dvl/svn-to-git/repo@4918 46e82423-29d8-e211-989e-002590a4cdd4

commit abc25a79a107e2ebe67a95668a978aca6c79537a
Author: Dan Langille <dan@langille.org>
Date:   Wed Oct 25 15:19:31 2017 +0000

    First release



    git-svn-id: file:///usr/home/dvl/svn-to-git/repo@4915 46e82423-29d8-e211-989e-002590a4cdd4

commit cb2b3410a8528d2b6fcab8183347734d2712ec99
Author: Dan Langille <dan@langille.org>
Date:   Wed Oct 25 14:42:43 2017 +0000

    Copy to trunk, so we can do branches etc



    git-svn-id: file:///usr/home/dvl/svn-to-git/repo@4911 46e82423-29d8-e211-989e-002590a4cdd4

commit 6e4da5d07de3769b617264010ca867a93dc5d877
Author: Dan Langille <dan@langille.org>
Date:   Wed Oct 25 14:36:28 2017 +0000

    Initial import

    git-svn-id: file:///usr/home/dvl/svn-to-git/repo@4910 46e82423-29d8-e211-989e-002590a4cdd4
```

**Comment by dlangille** [comment]
I'm looking here:

https://github.com/FreshPorts/periodics/blame/main/everythreeminutes/100.fp_system_status - click on Blame

https://github.com/FreshPorts/periodics/commits/main/everythreeminutes/100.fp_system_status

Looks like it came from tags, not trunk.

![Screenshot 2024-12-19 at 11 08 33 AM](https://github.com/user-attachments/assets/df0cf79f-d734-46ea-9158-9bcf20e86032)

**Comment by dlangille** [comment]
See also https://github.com/FreshPorts/periodics/commits/main/ - the commit history is centered around files outside `periodics`

**Comment by calebpower** [comment]
There is a filter-repo command that I can take a shot at to see if it clears up what would otherwise be empty commits.

**Comment by calebpower** [comment]
Okay, how about that? Here's what I did:

```
# some redacted (for ease of reading, to ignore fumbles)
[cpower@matrix ~/projects/code/freshports/periodics]$ history
  655  git clone git@github.com:freshports/periodics
  657  cd periodics/
  659  git checkout HEAD~1
  662  git filter-repo --subdirectory-filter periodics/trunk --force
  665  aria2c -x5 https://raw.githubusercontent.com/FreshPorts/periodics/refs/heads/main/LICENSE.txt
  668  git add --all
  669  git commit -m "add LICENSE.txt"
  682  git remote add origin git@github.com:freshports/periodics
  692  git push origin HEAD:main --force
```

**Comment by dlangille** [comment]
That has all the right commit history I think. For example, when comparing here, it seems right to me:

* https://svn.freshports[.]org/viewvc.cgi/freshports-1/periodics/?view=log
* https://github.com/FreshPorts/periodics/commits/main/

Now, how can we get the tags?

**Comment by calebpower** [comment]
hmmm... well I was having issues actually pulling the svn repo down locally via viewvc (very quick research indicates that maybe a tarball feature can be enabled, but that in general you can't "check it out" like a git repo... though that also might just be pebcak on my end).

I was thinking a quick scraper to pull the tag messages/timestamps, comparing them to git commits, and then pushing tags up that way. But that's definitely the dirty method.

**Comment by dlangille** [comment]
I'll get you a copy you can download.

**Comment by dlangille** [comment]
Please try fetching `x8dtu.freshsource[.]org/freshports-1.tar.gz` and let me know when you have it.

**Comment by calebpower** [comment]
got it (thanks!)

```
[cpower@matrix ~/projects/code/freshports]$ sha256sum freshports-1.tar.gz
c20e4b746aa807ef57e7c42be1bb237be7d9c07c8af54e11d462dbfbc26bb6d7  freshports-1.tar.gz
```

**Comment by dlangille** [comment]
```
% ls -l freshports-1.tar.gz 
-rw-r--r--  1 root 1002 33127908 2024.12.22 14:27 freshports-1.tar.gz
% md5 freshports-1.tar.gz 
MD5 (freshports-1.tar.gz) = 590e5c2816f4b0f344bda3bc8f2388ee
```

There is a problem

Ohh wait...

```
% sha256sum freshports-1.tar.gz
c20e4b746aa807ef57e7c42be1bb237be7d9c07c8af54e11d462dbfbc26bb6d7  freshports-1.tar.gz
```

Please carry on. ;)

**Comment by calebpower** [comment]
Okay, so here's what I've got, should be most of the non-destructive operations. But wanted to run my thought process by you real quick. Script for reference:

```sh
#!/usr/local/bin/bash

if [ "$#" -ne 3 ]; then
  printf 'Usage:   %s <svn_url> <svn_repo> <git_dir>\n' "$0"
  printf 'Example: %s svn://127.0.0.1/freshports-1 periodics /freshports/periodics\n' "$0"
  exit 1
fi

SVN_URL="$1"
SVN_REPO="$2"
GIT_LOCAL="$3"

cd "$GIT_LOCAL"

svn_tags=($(svn list "${SVN_URL}/${SVN_REPO}/tags" | sed -e 's/\///g'))
for svn_tag in ${svn_tags[@]}; do
  svn_rev=$(svn info "${SVN_URL}/${SVN_REPO}/tags/${svn_tag}" | grep -E '^Last Changed Rev:' | cut -d' ' -f4)
  svn_log="$(svn log -r $svn_rev "${SVN_URL}" --xml)"
  author=$(echo "${svn_log}" | htmlq --text 'author')
  svn_date="$(echo "${svn_log}" | htmlq --text 'date' | sed -E 's/T/ /; s/\..*Z$//') +0000"
  svn_msg="$(echo "${svn_log}" | htmlq --text 'msg' | sed "s/^'//;s/'\$//")"

  git_log="$(git log --until="${svn_date}" --max-count=1 --author-date-order --pretty=format:"%h %ad %s" --date=iso)"
  git_commit=$(echo $git_log | cut -d' ' -f1)
  git_date=$(echo $git_log | cut -d' ' -f2,3,4)
  git_msg=$(echo $git_log | cut -d' ' -f5-)

  printf -- '--------------------------\n'
  printf 'SVN tag: %s; rev: %s; author: %s; timestamp: %s\n' \
      "${svn_tag}" "${svn_rev}" "${author}" "${svn_date}"
  printf 'SVN message: %s\n' "${svn_msg}"
  printf 'GIT commit: %s; timestamp: %s\n' "${git_commit}" "${git_date}"
  printf 'GIT message: %s\n' "${git_msg}"
done
```

Truncated stdout:

```
[cpower@matrix ~/projects/code/freshports]$ ./port_tags.sh svn://127.0.0.1/freshports-1 periodics /home/cpower/projects/code/freshports/periodics
--------------------------
SVN tag: 1.0.0; rev: 4919; author: dan; timestamp: 2017-10-25 15:35:02 +0000
SVN message:
GIT commit: ae1d377; timestamp: 2017-10-25 15:19:23 +0000
GIT message: mkdir tags
--------------------------
SVN tag: 1.0.10; rev: 5059; author: dan; timestamp: 2018-05-05 20:19:33 +0000
SVN message: better messages
GIT commit: 994bea1; timestamp: 2018-05-05 20:17:40 +0000
GIT message: Better messages
--------------------------
SVN tag: 1.0.11; rev: 5078; author: dan; timestamp: 2018-05-06 13:18:18 +0000
SVN message: remove duplicate numbers in logger messages
GIT commit: 433bdc2; timestamp: 2018-05-06 13:13:20 +0000
GIT message: Don't double up on the number in logger

# etc., etc...
```

So I think what's happening (and correct me if wrong) is that creating a tag in svn is sort of a commit on its own, and when I cleared out all of the "empty commits" (commits that didn't change anything in 'periodics') the svn tags were caught in the mix. But if I'm right, this is okay because to translate a tag over to git exactly the way it's done in svn would require an empty commit... and tags in git work differently.

So what I've done instead is I've had the script reference the most recent git commit in the log with respect to the tag's timestamp. It means that the tag's "message" will necessarily be different than the message of the commit itself, but I think that's okay because we can annotate tags.

**Comment by calebpower** [comment]
```
[cpower@matrix ~/projects/code/freshports/periodics]$ git show 1.0.11
tag 1.0.11
Tagger: Caleb L. Power <cpower@axonibyte.com>
Date:   Sun Dec 22 11:52:57 2024 -0500

remove duplicate numbers in logger messages

commit 433bdc2c01902f674222552a5c2209792863a27c (tag: 1.0.11)
Author: Dan Langille <dan@langille.org>
Date:   Sun May 6 13:13:20 2018 +0000

    Don't double up on the number in logger


    git-svn-id: file:///usr/home/dvl/svn-to-git/repo@5075 46e82423-29d8-e211-989e-002590a4cdd4

diff --git a/daily/100.fp_archive_messages b/daily/100.fp_archive_messages
index fe47e86..469071a 100644
--- a/daily/100.fp_archive_messages
+++ b/daily/100.fp_archive_messages
@@ -18,7 +18,7 @@ logger -t FreshPorts "FreshPorts - archiving messages:"
 case "$fp_archive_messages_enable" in
        [Yy][Ee][Ss])
         echo ""
-       logger -t FreshPorts "into 100.100.fp_archive_messages - archiving messages:"
+       logger -t FreshPorts "into 100.fp_archive_messages - archiving messages:"
         echo "cd $fp_scripts_dir && ./archive-messages.sh 1" | nice -n 5 su -fm $fp_freshports_user || rc=3
         ;;
```

Seems to have translated alright into my local git repo instance.

**Comment by dlangille** [comment]
Yes,  I noticed that too.  Tagging  in  `subversion` is a commit.

**Comment by calebpower** [comment]
I think there's a way for me to preserve tag timestamps as well, so I'm looking into that.

**Comment by calebpower** [comment]
Ok, that's done-- let me know if that looks right to you. Updated tag porting script at new [gist](https://gist.github.com/calebpower/1cb746df582d75d60af28a38dd0d1730) for now.

**Comment by dlangille** [comment]
Those tags look good to me. What's next on this repo?

**Comment by calebpower** [comment]
As far as this importing this repo goes, I think that's it unless there's anything else you'd like done with it. I do need to complete issue FreshPorts/periodics#2 but I can do that through a PR and w/o admin access.

If you'd like me to go through the other repos to get them out of the "basement" so-to-speak, I'd be happy to take care of that first. Don't know if you want some or all of them converted.

**Comment by dlangille** [comment]
I appreciate the conversion work you are doing. I feel it's very important to get that done. Yes, please let's do more repos and get them online.

A main issue, listing the repos to convert, with links to the individual issues, sounds like a good idea.  I'll create that next. First up, would be the ports (see FreshPorts/ports#1, because that will need updating after FreshPorts/periodics#1 is done).

Not everything in the ports repo is FreshPorts related. I'll update that issue.

**Comment by calebpower** [comment]
Happy to help!

**Comment by dlangille** [comment]
> Not everything in the ports repo is FreshPorts related. I'll update that issue.

That part is done.

**Comment by dlangille** [comment]
@calebpower  are you OK with us closing this issue for now? I think the conversion is done.

**Comment by calebpower** [comment]
Absolutely.
